language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t jrowbotham/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true jrowbotham/docker-react npm run test
