version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      #  bookmark node_mods so it doesnt copy that
      - /app/node_modules
      #  map current  wd to app folder
      - .:/app
    # https://github.com/facebook/create-react-app/issues/8688
    tty: true
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    tty: true
    command: ["npm", "run", "test"]
